# Generated by Django 4.0.4 on 2022-05-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='frequency',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
